#!/bin/bash

APP="lo_price"

git commit -am "$1"
git push

ssh -t -A -S none -q -o ConnectTimeout=60 ex@extrapost.ru "cd ~/$APP && git pull && source ~/.profile && MIX_ENV=prod mix ecto.migrate && MIX_ENV=prod mix release --overwrite && ./_build/prod/rel/$APP/bin/$APP restart"